name: armTemplateDeployment

on:
  push:
    branches:
      -main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      # - name: Deploy Resource Group rg-githubactions with AZ CLI
      #   uses: Azure/cli@1.0.4
      #   with: 
      #     inlinescript: |
      #       az deployment sub create --location "East US" --template-file ./arm-templates/resourcegroup.json


      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 6109bd4c-4a39-4cac-b2f3-d3aa02570c4e
          region: Australia East
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions
